### PR TITLE
Re-export GenericArray to allow users to avoid version conflicts

### PR DESCRIPTION
**Pull request by peterjoel**

### CODE REVIEW

**Comment by tarcieri** [comment]
It’s already re-exported as `hmac::crypto_mac::generic_array`

**Comment by peterjoel** [comment]
This is re-exported from a dependency, so it's hard to find that information unless you go to look at that crate's documentation too.

I feel like it should be good practice to explicitly re-export any types that you use in a public API, regardless of transitive re-exports.

**Comment by tarcieri** [comment]
@peterjoel I think it might make sense to directly re-export `generic_array` for convenience, but that it's better not to pollute the toplevel namespace with a bunch of re-exported types from other crates. That makes it less clear which crates those types are coming from.

Also note that `GenericArray` supports a number of conversions (e.g. `Into`) which let you avoid directly referencing it by name in your code.

Can't wait for const generics when all these issues will be moot. 😉

**Comment by peterjoel** [comment]
@tarcieri  That's true. I actually used `impl Deref<Target = [u8]>` in the end.

**Comment by peterjoel** [comment]
> Can't wait for const generics when all these issues will be moot. 😉

There'll still be issues with transitive dependencies of _other_ types of course...

**Pull request closed without merging**
