### PR TITLE
Add poly1305 crate (derived from rust-crypto)

### PR DESCRIPTION
**Pull request by tarcieri**
This PR adds an initial `poly1305` crate based on the `rust-crypto` implementation of Poly1305 (which in turn is a translation of [poly1305-donna](https://github.com/floodyberry/poly1305-donna)):

https://github.com/DaGenix/rust-crypto/blob/9a4d8f279b643b8ae006e442141571fc7a85a3cf/src/poly1305.rs

I've done the minimal work to adapt it to `crypto_mac::Mac` and generally fact it more like the rest of `RustCrypto/MACs`.

Performance is good enough for my purposes, but could be better w\ SIMD acceleration. Benchmark using the `crypto-mac` crate's `bench!` macro on a 3.1 GHz Intel Core i7:

```
running 4 tests
test bench1_10    ... bench:          21 ns/iter (+/- 1) = 476 MB/s
test bench2_100   ... bench:         100 ns/iter (+/- 21) = 1000 MB/s
test bench3_1000  ... bench:         900 ns/iter (+/- 250) = 1111 MB/s
test bench3_10000 ... bench:       8,937 ns/iter (+/- 1,075) = 1118 MB/s
```

I will throw the code into Godbolt so we can do some inspection of whether or not the implementation appears to be constant-time on select platforms.

### CODE REVIEW

**Comment by tarcieri** [comment]
@newpavlov well I went ahead and did the thing we talked about not doing originally for now 😉 

That's mostly to make it a straightforward translation of the original `rust-crypto` code, but I think it's worth considering whether it's reasonable or safe to treat Poly1305 as a `crypto_mac::Mac`, or if we need a different-but-similarly-shaped trait for universal hashing functions (from which MACs can be based, when e.g. combined with a cipher).

**Comment by tarcieri** [comment]
Here's the code in godbolt. I didn't see anything obviously non-constant time in a quick pass through the generated assembly with `-Copt-level=3`, but will scrutinize it more:

https://godbolt.org/z/T-7EP_

**Comment by tarcieri** [comment]
@newpavlov well, I've fixed all of my own nits with this and would say it's ready for review.

I ended up removing the `crypto_mac::Mac` impl for now. If someone actually desires Poly1305-AES (which seems unlikely, and should probably be gated under a cargo feature), it seems appropriate for that, but not for Poly1305 itself as a one-time authenticator.

**Comment by tarcieri** [comment]
Updated godbolt here: https://godbolt.org/z/V9zoPr

**Comment by tarcieri** [comment]
@newpavlov can you give me access to the `poly1305` crate to cut a release of this? (unless you think it needs more work)

**Comment by newpavlov** [comment]
@tarcieri 
Done! I haven't reviewed code in depth yet, but feel free to publish without waiting on me!

**Comment by tarcieri** [comment]
@newpavlov thanks! I'd like to circle back at some point and add SIMD support, but this seems like a start

**Pull request merged**
