### PR TITLE
[WIP] Add Wycheproof test vectors

### PR DESCRIPTION
**Pull request by daviddrysdale**
This includes local copies of the macro in https://github.com/RustCrypto/traits/pull/568

### CODE REVIEW

**Comment by daviddrysdale** [comment]
(I *think* that moving to use the `new_trunc_test!` from https://github.com/RustCrypto/traits/pull/568 is currently blocked by needing updates here to allow for the removal of `cipher` as a dependency of `crypto-mac` in https://github.com/RustCrypto/traits/pull/537, but I'm not completely sure&hellip;)

**Comment by newpavlov** [comment]
I've added Wycheproof test files generated by you in #95, so I think we can close this PR.

**Comment by daviddrysdale** [comment]
I can't see the test vectors in #95 &ndash; am I missing something?

**Comment by newpavlov** [comment]
Whops, I forgot to push. :) Fixed.

**Pull request closed without merging**
